---
title: "Camera Temperature"
author: "Nima Hamedani-Raja"
date: "27/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Camera_temperature}
######### INIT 

source("Functions/General/INIT.R")

########## CameraTemperature

source("Functions/Analysis/get_temperature.R")

if(!file.exists("Data/camera_temperature.csv")){
    DF_temperature <- 
        do.call("bind_rows", 
                lapply(
                    list.files(
                        config %>% filter(type == "meta_folder_analysis") %>% select(value) %>% as.character(), 
                        full.names = TRUE), 
                    get_temperature))  %>% 
        mutate(year_month_number = as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S") %>% format("%Y-%m")) %>% 
        mutate(year_month = as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S") %>% format("%Y-%b")) %>% 
        mutate(year = as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S") %>% format("%Y")) %>% 
        mutate(month_number = as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S") %>% format("%m")) %>% 
        mutate(month = as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S") %>% format("%b")) %>% 
        mutate(yearmon = as.yearmon(as.POSIXct(DateTimeOriginal ,format="%Y:%m:%d %H:%M:%S")));
    
    write.csv(DF_temperature, "Data/camera_temperature.csv", row.names = FALSE)
} else {DF_temperature <- read.csv("Data/camera_temperature.csv")}

DF_temperature %>% filter(!is.na(CameraTemperature)) %>%
    ggplot(aes(x = yearmon, y = CameraTemperature, group = yearmon)) + 
    geom_boxplot(fill = "lightblue") +
    ggtitle("Camera Temperature v. Month")

DF_temperature %>% filter(!is.na(CameraTemperature)) %>%
    ggplot(aes(x = CameraTemperature, colour = month)) +
    geom_density()
```